feature add of category
ericraj/share-docs pull request #11
Opened 2021-04-20 12:17 UTC by OloMola3

2021-04-20 12:28 UTC, ericraj commented on backend/src/resolvers/categories/category.ts
> +  async createCategory(@Arg("inputs") inputs: CategoryInput): Promise<CategoryResponse> {
add is auth middleware here to check if user is connected or not
@UseMiddleware(isAuth)

2021-04-20 12:29 UTC, ericraj requested changes

2021-04-20 12:29 UTC, ericraj commented on backend/src/resolvers/categories/category.ts
> +  @Mutation(() => CategoryResponse)
add is auth middleware here to check if user is connected or not
@UseMiddleware(isAuth)

2021-04-20 12:32 UTC, ericraj commented on backend/src/resolvers/categories/category.ts
> +  @Mutation(() => CategoryResponse)
rename your file category.ts to addCategory.ts because we must separe CRUD resolvers so as not to have a file too long

2021-04-20 12:36 UTC, ericraj commented on backend/src/resolvers/categories/category.ts
> +      const result = await getConnection()
*No need for all that*
get userId from session

example : 
```javascript
return Post.create({ ...input, creatorId: req.session!.userId }).save();
```

2021-04-20 12:38 UTC, ericraj commented on backend/src/resolvers/categoryInput.ts
> +import { InputType, Field } from "type-graphql";
dont need userId here, see https://github.com/ericraj/share-docs/pull/11/files#r616641365

2021-04-20 14:42 UTC, ericraj commented on backend/src/utils/validateCategory.ts
> +
dont check userId here

2021-04-20 14:42 UTC, ericraj commented on backend/src/utils/validateCategory.ts
> +    return [{ field, message: "Veuillez remplir tout les champ" }];
use a simple english sentence please

2021-04-20 14:42 UTC, ericraj commented on backend/src/resolvers/categoryInput.ts
> +  creatorId: number;
dont need userId here, see https://github.com/ericraj/share-docs/pull/11/files#r616641365

2021-04-20 14:42 UTC, ericraj commented on backend/src/resolvers/categories/category.ts
> +      const result = await getConnection()
*No need for all that*
get userId from session

example : 
```javascript
return Post.create({ ...input, creatorId: req.session!.userId }).save();
```

2021-04-20 14:42 UTC, ericraj commented on backend/src/resolvers/categories/category.ts
> +  @Mutation(() => CategoryResponse)
add is auth middleware here to check if user is connected or not
```javascript
@UseMiddleware(isAuth)
```

2021-04-20 14:42 UTC, ericraj commented on backend/src/resolvers/categories/category.ts
> +import { Category } from "../../entities/Category";
rename your file category.ts to addCategory.ts because we must separe CRUD resolvers so as not to have a file too long

2021-04-20 14:42 UTC, ericraj commented on backend/src/resolvers/categories/category.ts
> +export default class CategoryResolver {
rename to AddCategoryResolver

2021-04-20 14:54 UTC, OloMola3 commented on backend/src/resolvers/categoryInput.ts
> +  creatorId: number;
i don't understand

2021-04-22 06:37 UTC, ericraj commented on backend/src/resolvers/categories/getCategories.ts
> +    const categories = await getConnection().query(`SELECT * FROM categories`);
change query for the pagination

2021-04-22 06:37 UTC, ericraj commented on backend/src/resolvers/categories/getCategories.ts
> +      page: 0,
this value must not `0`, change it to `page` simply

idem for skip

2021-04-22 13:16 UTC, ericraj approved these changes

2021-04-23 06:22 UTC, merged